export const MEALS = [
  {
    id: "1",
    name: "Phở bò tái chín",
    calories: 450,
    time: "30 phút",
    rating: 4.8,
    emoji: "🍜",
  },
  {
    id: "2",
    name: "Salad rau trộn",
    calories: 180,
    time: "15 phút",
    rating: 4.5,
    emoji: "🥗",
  },
  {
    id: "3",
    name: "Cơm gà xối mỡ",
    calories: 520,
    time: "20 phút",
    rating: 4.7,
    emoji: "🍚",
  },
  {
    id: "4",
    name: "Bún bò Huế",
    calories: 480,
    time: "35 phút",
    rating: 4.9,
    emoji: "🍲",
  },
  {
    id: "5",
    name: "Bánh mì thịt",
    calories: 320,
    time: "10 phút",
    rating: 4.6,
    emoji: "🥖",
  },
  {
    id: "6",
    name: "Smoothie trái cây",
    calories: 150,
    time: "5 phút",
    rating: 4.4,
    emoji: "🥤",
  },
];
